### ISSUE TITLE
To-Do List for Remaining Features

### ISSUE THREAD

**Issue by jillianw** [jillianw/web-app__swimming-competition#1]
- [x] Fix updating forms so that Awards and Event Detail changes actually get saved (currently not working)
- [x] Build pages for viewing just one record. Put links to these pages in sensible places in your web application.
- [ ] List all competitors for just one event (which is identified by its ID). Example path for such a page: /events/4/competitors.
- This could also just be some new content you add to the view for one event's details page.
- Everywhere that a school's name is displayed, also show the name of the conference. E.g. if a competitor's details page shows their school's name, it should also show the conference.
- List the top three performers in an event. You can choose where this information goes--think of a sensible place.
- [x] Think of one more feature to add and get approval for it. Then implement that feature.
- [x] The list of the top three performers in an event should not be available until the event is complete. If all competitors for that event have finished, and if all of their times have been entered, then show the top 3 performers. If not, show message that event is not over.
- [x] Where else on the website is information not supposed to be accessible until (or after) a certain point? Think of a new feature related to this and get approval for it. Then implement it.
- [x] If the administrator deletes a competitor, the system should automatically delete all of that competitor's signups/awards/results/etc.
- [x] Similarly, if the administrator deletes a team, the system should automatically delete all of that team's competitors. (Which means that then all of those competitors' signups/awards/results/etc get deleted!)
- [x] If the administrator tries to delete a conference, then the system should first check if there are any teams in that conference. If there are none, then the system should delete the conference. But if there are teams in the conference, then the system should not delete the conference--it should tell the administrator to first go manually delete those teams (or change their conference).
- [x] Implement a feature in the system that lets admin "lock" an event--after which point that event's information cannot be altered. "Locking" is something the administrator must do manually to an event. 
- (For this to work, there must be some column in the events table called "locked" (for example), which stores boolean data. (This is a valid data type for the define_schema.rb file.) You will need to add this column at some point.)
- (Admin should not be able to add a new result for that event, alter the values of any results for that event, sign up a new competitor for that event or delete the event.)

<b>SPEND HALF OF TIME THIS WEEKEND WORKING ON BINARY, OTHER HALF OF TIME GETTING UNIT TESTS DONE FOR COMPETITION APP</b>

and journals...
